on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: docker
    container:
      image: docker.io/docker:cli
    steps:
      -
        name: Login to Forgejo container registry
        uses: https://code.forgejo.org/docker/login-action@v3
        with:
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: git.byjp.me/${{ github.repository }}:latest
